version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    image: 641128561021.dkr.ecr.us-east-1.amazonaws.com/bmk:latest
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    container_name: team_omega_c
    volumes:
      - .:/team_omega
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    

volumes:
  dev-db-data:

