version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:


volumes:
  dev-db-data:
