# Generated by Django 4.0.5 on 2022-07-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
