# Generated by Django 4.0.5 on 2022-07-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cinema_id",
            field=models.ManyToManyField(to="coreapis.cinema"),
        ),
    ]
