# Generated by Django 4.0.5 on 2022-07-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0002_rename_cinems_screen_id_seat_cinema_screen_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_no",
            field=models.CharField(max_length=8),
        ),
    ]
