# Generated by Django 4.0.5 on 2022-07-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0002_movie_cinema_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="seat_id",
            new_name="seat",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="show_time_id",
            new_name="show_time",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="cinema",
            old_name="city_id",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="cinemascreen",
            old_name="cinema_id",
            new_name="cinema",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="cinema_id",
            new_name="cinema",
        ),
        migrations.RenameField(
            model_name="seat",
            old_name="cinema_screen_id",
            new_name="cinema_screen",
        ),
        migrations.RenameField(
            model_name="showtime",
            old_name="cinema_screen_id",
            new_name="cinema_screen",
        ),
        migrations.RenameField(
            model_name="showtime",
            old_name="movie_id",
            new_name="movie",
        ),
    ]
