# Generated by Django 4.0.5 on 2022-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0003_alter_movie_release_date_alter_seat_seat_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateTimeField(),
        ),
    ]
