# Generated by Django 4.0.5 on 2022-07-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapis', '0003_rename_seat_id_booking_seat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='cinemascreen',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='cinemascreen',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='city',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='city',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='deleted_by_cascade',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cinema',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cinemascreen',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showtime',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
