# Generated by Django 4.0.5 on 2022-07-12 07:05

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coreapis', '0005_alter_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at_utc',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 12, 7, 5, 3, 776450, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='modified_at_utc',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='created_at_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cinema',
            name='modified_at_utc',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cinemascreen',
            name='created_at_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinemascreen',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cinemascreen',
            name='modified_at_utc',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='city',
            name='created_at_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='modified_at_utc',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='modified_at_utc',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='created_at_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='modified_at_utc',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='created_at_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showtime',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showtime',
            name='modified_at_utc',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
