# Generated by Django 4.0.5 on 2022-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0005_alter_city_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
