# Generated by Django 4.0.5 on 2022-07-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0005_alter_movie_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
