# Generated by Django 4.0.5 on 2022-07-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0006_booking_deleted_booking_deleted_by_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="showtime",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="showtime",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
