# Generated by Django 4.0.5 on 2022-07-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0006_alter_city_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="cinema",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="cinemascreen",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="city",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="showtime",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="booking",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="cinema",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cinema",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="cinemascreen",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cinemascreen",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="city",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="seat",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="showtime",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="showtime",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
