# Generated by Django 4.0.5 on 2022-07-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapis', '0007_booking_deleted_at_cinema_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='cinemascreen',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='city',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='is_deleted',
        ),
    ]
