# Generated by Django 4.0.5 on 2022-07-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0006_booking_created_at_utc_booking_is_deleted_and_more"),
        ("coreapis", "0007_seat_deleted_seat_deleted_by_cascade_and_more"),
    ]

    operations = []
