# Generated by Django 4.0.5 on 2022-07-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapis", "0008_merge_20220712_1442"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="cinema",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="cinemascreen",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="city",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="showtime",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="cinema",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cinema",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="cinemascreen",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cinemascreen",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="city",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
