name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: shreyagrawal003
          password: shrey003@
      - uses: actions/checkout@v3
      - name: Analysing the code with pylint
        run: |
          docker compose run --rm api sh -c pylint ./book_my_show/*.py
